title: AWS Notes
description: AWS components and services notes for quick reference.
remote_theme: just-the-docs/just-the-docs

url: "https://dpk361.github.io"
baseurl: "/aws-notes"

source: docs/

search_enabled: true

aux_links:
  GitHub Repository:
    - https://github.com/dpk361/aws-notes
